# Generated by Django 5.0.1 on 2024-02-01 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Strategy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("variable_expenses", models.FloatField(verbose_name="Variable Expenses")),
                ("fixed_expenses", models.FloatField(verbose_name="Fixed Expenses")),
                ("investments", models.FloatField(verbose_name="Investments")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "user_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Estrategia",
        ),
    ]
