# Generated by Django 5.0.1 on 2024-01-23 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Investimento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="Data")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("FIIs", "FUNDO IMOBILIÁRIO (FII)"),
                            ("CDB", "CERTIFICADO DE DEPÓSITO BANCÁRIO (CDB)"),
                            ("ACAO", "AÇÃO"),
                            ("CRIPTO", "CRIPTOMOEDA"),
                        ],
                        max_length=100,
                        verbose_name="Tipo de Investimento",
                    ),
                ),
                ("value", models.FloatField(verbose_name="Valor")),
                ("name", models.CharField(max_length=100, verbose_name="Nome do Investimento")),
                ("profitability", models.FloatField(verbose_name="Rentabilidade")),
                (
                    "user_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
