# Generated by Django 5.0.1 on 2024-02-01 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portions",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="Date")),
                ("portion", models.PositiveSmallIntegerField(verbose_name="Current Portion")),
                ("max_portion", models.PositiveSmallIntegerField(verbose_name="Portion Quantity")),
            ],
        ),
        migrations.RemoveField(
            model_name="gastos",
            name="parcelas_id",
        ),
        migrations.RemoveField(
            model_name="gastos",
            name="user_id",
        ),
        migrations.CreateModel(
            name="Expenses",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "type",
                    models.CharField(
                        choices=[("FIXO", "FIXO"), ("INVESTIMENTO", "INVESTIMENTO"), ("VARIAVEL", "VARIAVEL")],
                        max_length=50,
                        verbose_name="Expense Type",
                    ),
                ),
                ("value", models.FloatField(verbose_name="Value")),
                ("is_entry", models.BooleanField(default=False, verbose_name="Is Entry")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("portions", models.CharField(max_length=10, verbose_name="Portion")),
                (
                    "user_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "portions_id",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="expenses.portions"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Parcelas",
        ),
        migrations.DeleteModel(
            name="Gastos",
        ),
    ]
